### ISSUE TITLE
nimble file should pin to nim 1.4.8 until this works without problem in 1.6

### ISSUE THREAD

**Issue by bung87** [haxscramper/hmisc#8]

**Comment by disruptek** [comment]
I don't know if Nimble even cares about the `nim` version requirement, but this would just add a burden for people trying to make it work in 1.6.0.

**Comment by bung87** [comment]
It's like `nim >= 1.2.2 & < 2.0.0 ` in nimble, I ran a project (5 months don't touched) the hmisc results three kinds of error ,  one is about clang compiler -pg flag, one related to std lib , one I don't remember...

in the end nim 1.4.8 and hmisc 0.11.14 works fine.

**Comment by haxscramper** [comment]
I will soon push the 1.6.0 update, I've just been busy with trying to migrate away from nimble (to nimph) and into 1.6.0, as well as fixing up some tests.

**Comment by bung87** [comment]
glad to hear that, thank you for your works on this project.

**Comment by haxscramper** [comment]
CI passes for 1.6.0, so this can be considered solved
